/**
 * Copyright (c) 2010 Yahoo! Inc. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */

package site.ycsb.generator;

/**
 * A generator that is capable of generating integers as well as strings
 * 
 * @author cooperb
 *
 */
public abstract class IntegerGenerator extends NumberGenerator
{
	private Integer lastInt;
	
	/**
	 * Set the last value generated. IntegerGenerator subclasses must use this call
	 * to properly set the last value, or the lastValue() and lastString() calls won't work.
	 */
	protected void setLastInt(Integer last)
	{
        lastInt = last;
	}

    @Override
    public Number nextValue() {
        Integer next = nextInt();
        setLastValue(next);
        setLastInt(next);
        return next;
    }

    @Override
    public Number lastValue() {
        return lastInt != null ? lastInt : super.lastValue();
    }
	
	/**
	 * Return the previous int generated by the distribution. This call is unique to IntegerGenerator subclasses, and assumes
	 * IntegerGenerator subclasses always return ints for nextInt() (e.g. not arbitrary strings).
	 */
	public Integer lastInt()
	{
		return lastInt;
	}

    /**
     * Return the next value as an int. When overriding this method, be sure to call setLastInt() properly, or the lastValue() call won't work.
     */
    public abstract Integer nextInt();

    /**
	 * Return the expected value (mean) of the values this generator will return.
	 */
	public abstract double mean();
}
